# Introduzione a Numpy

### Requisiti
Installare numpy da termiinale con `pip install numpy` o `pip3 install numpy`

Importazione: `import numpy as np` (è una convenzione assegnare `np` come alias)

## Cos'è Numpy?
Numpy ci permette di gestire array multidimensionali



In [1]:
import numpy as np

# Indexing e Slicing
## Accesso agli elementi in un array NumPy

Negli array NumPy è possibile accedere agli elementi utilizzando **l'indicizzazione tra parentesi quadre `[]`**.

Per gli array multidimensionali si specifica un indice per ogni dimensione.

Ad esempio, dato l'array:



```python
A = np.array([
    [3, 5, 7],
    [2, 6, 4]
])


```
- **A[0,1]** accede all'elemento nella prima riga e seconda colonna. Ricordare: `A[riga,colonna]`
- A[:,:] prende tutte le righe e tutte le colonne (il simbolo `:` significa prendi tutto)
- A[:,1] tutte le righe della seconda colonna
- A[:2,:] accede alle prime due righe di tutte le colonne

La sintassi completa è: `start:stop:step`: -1 è lo step negativo che parte dalla fine:

- A[:1,:1-1]

Data la matrice:

```
A = np.array([
    [3, 5, 7, 9],
    [2, 6, 4, 8],
    [1, 0, 5, 3]
])
```
## Esercizio 1 — Accesso a un elemento

Stampare:

- l'elemento nella prima riga e seconda colonna

- l'elemento nella terza riga e quarta colonna

## Esercizio 2

Trasformare:

- prima colonna: 1,2,3
- seconda colonna: 4,5,6
- terza colonna: 7,8,9

(se volete usare arange e reshape ricordate di usare .T per trasporre la matrice)

## Esercizio 3

- Data la matrice risultante dall'esercizio 2, invertire prima le righe e poi le colonne.
- Seleziona le prime due righe e tutte le colonne con uno step di 2

### Broadcast
NumPy applica automaticamente operazioni tra array di dimensioni diverse replicando implicitamente i dati quando possibile. Nel caso di a = [1,2,3] moltiplicato con uno scalare 10, la moltiplicazione equivale concettualemnte a [1,2,3]*[10,10,10].

Ricordare la shape è data da `(n_righe, n_colonne)`. 

In [26]:
A = np.array([
    [3, 5, 7, 9],
    [2, 6, 4, 8],
    [1, 0, 5, 3]
])

# esercizio 1
print(f"ESERCIZIO 1")
print(A[0,1])
print(A[2,3])

# esercizio 2 trasformare la prima colonna in 1,2,3 
print(f"ESERCIZIO 2")
A[:,0] = [1, 2, 3]
# print(A)
A[:,1] = [4, 5, 6]
# print(A)
A[:,2] = [7, 8, 9]
# print(A)

# usando arange e reshape
print(f"Usando arange e reshape")
B = np.arange(1, 10).reshape(3, 3).T # la trasposta serve per scambiare righe e colonne
print(B)
A[:,0:3] = B
print(A)

# esercizio 3
print(f"ESERCIZIO 3")
A_inv_rows = A[::-1] # invertire le righe
print(f"Invertiamo le righe: \n{A_inv_rows}")
A_inv_cols = A_inv_rows[:,::-1] # invertire le colonne
print(f"Invertiamo le colonne: \n{A_inv_cols}")

print(f"Selezioniamo le prime 2 righe e le colonne pari (0 e 2): \n{A_inv_cols[:2,::2]}")




ESERCIZIO 1
5
3
ESERCIZIO 2
Usando arange e reshape
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7 9]
 [2 5 8 8]
 [3 6 9 3]]
ESERCIZIO 3
Invertiamo le righe: 
[[3 6 9 3]
 [2 5 8 8]
 [1 4 7 9]]
Invertiamo le colonne: 
[[3 9 6 3]
 [8 8 5 2]
 [9 7 4 1]]
Selezioniamo le prime 2 righe e le colonne pari (0 e 2): 
[[3 6]
 [8 5]]


In [29]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.zeros((2, 3))

print(a)
print(f"Shape di a: {a.shape}")
print(f"Shape di b: {b.shape}")
print(f"Shape di c: {c.shape}")
print("---Manipolazione di array---")

nuovo_array = a * c + b
print(f"nuovo_array:\n{nuovo_array}") #Cosa notate stampando questo array? Perché accade?


print("---Creazione di una matrice formata da a + b")
D = a + b
print(f"matrice D:\n{D}")

# creiamo sempre una nuova matrice per fare le aggiunte
print("---Creazione di una matrice E aggiungendo una riga a D--") 
E = D.copy() # per evitare di modificare D
E = np.vstack([E, a]) # aggiungiamo a come nuova riga
print(f"matrice E:\n{E}")


print("---Creazione di una matrice F aggiungendo il vettore a come colonna alla matrice E---")
F = np.hstack([E, a.reshape(-1, 1)]) # aggiungiamo a come nuova colonna
print(f"matrice F:\n{F}")

print("---Popolare la prima riga di c usando la seconda riga di D---")
c[0] = D[1]
print(f"matrice c:\n{c}")



[1 2 3]
Shape di a: (3,)
Shape di b: (2, 3)
Shape di c: (2, 3)
---Manipolazione di array---
nuovo_array:
[[1. 2. 3.]
 [4. 5. 6.]]
---Creazione di una matrice formata da a + b
matrice D:
[[2 4 6]
 [5 7 9]]
---Creazione di una matrice E aggiungendo una riga a D--
matrice E:
[[2 4 6]
 [5 7 9]
 [1 2 3]]
---Creazione di una matrice F aggiungendo il vettore a come colonna alla matrice E---
matrice F:
[[2 4 6 1]
 [5 7 9 2]
 [1 2 3 3]]
---Popolare la prima riga di c usando la seconda riga di D---
matrice c:
[[5. 7. 9.]
 [0. 0. 0.]]


## Generare matrici 
## Esercizio: Costruzione di una matrice con slicing NumPy

Utilizzando **NumPy**, costruire una matrice quadrata `7×7` con la seguente struttura:

```
1 1 1 1 1 1 1
1 2 2 2 2 2 1
1 2 0 0 0 2 1
1 2 0 8 0 2 1
1 2 0 0 0 2 1
1 2 2 2 2 2 1
1 1 1 1 1 1 1
```

### Vincoli

Costruire la matrice **partendo da una matrice iniziale** e modificando i valori usando:

- slicing degli array NumPy
- assegnazioni su sotto-matrici

Suggerimento:

1. creare inizialmente una matrice piena di `1`
2. modificare progressivamente le regioni interne della matrice usando lo slicing

### Output atteso

Stampare la matrice finale che deve corrispondere a quella descritta.

In [32]:
# N.B: #. array[riga_start:riga_end, col_start:col_end]
A = np.ones((7,7))
B = np.full((5,5), 2)
C = np.zeros((3,3))
C[1,1] = 8
A[1:6, 1:6] = B
A[2:5, 2:5] = C
print(f"matrice A finale:\n{A}")


matrice A finale:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2. 2. 1.]
 [1. 2. 0. 0. 0. 2. 1.]
 [1. 2. 0. 8. 0. 2. 1.]
 [1. 2. 0. 0. 0. 2. 1.]
 [1. 2. 2. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


# Simulazione: spegnere alcune connessioni in una rete neurale
## Rappresentazione dei pesi di una rete neurale con matrici

In una rete neurale **ogni layer può essere visto come una moltiplicazione tra una matrice e un vettore**.

Sia:

- **x** = vettore di input  
- **W** = matrice dei pesi  
- **b** = vettore di bias  

L'output è dato da:

\[
y = Wx + b
\]


Il layer applica **una trasformazione lineare seguita eventualmente da una funzione di attivazione**.

In questo modo, **ogni layer della rete neurale è rappresentato da una matrice di pesi** che collega i neuroni del layer precedente con quelli del layer successivo.

## Rappresentazione di una rete neurale con matrici 

Consideriamo una rete neurale composta da più layer.  
Ogni layer è rappresentato da **una matrice di pesi** che collega i neuroni del layer precedente con quelli del layer successivo.

Se:
- \(x\) è il vettore di input
- \(W_1\) è la matrice dei pesi tra input e primo layer nascosto
- \(W_2\) è la matrice dei pesi tra primo layer nascosto e output
- \(b_1, b_2\) sono i bias (assumiamo essere 1, per semplicità)

le trasformazioni della rete possono essere scritte come:

\[
h = xW_1 + b_1
\]

\[
y = hW_2 + b_2
\]

dove:
- \(h\) rappresenta le attivazioni del layer nascosto
- \(y\) rappresenta l'output della rete

Le matrici dei pesi hanno dimensioni determinate dal numero di neuroni nei layer.  
Ad esempio:

- input: **3 neuroni**
- hidden layer: **4 neuroni**
- output layer: **2 neuroni**

In questa situazione viene fatto il prodotto matriciale tra l'input e la matrice dei pesi che collega i neuroni di input con quelli dell'hidden layer. Il risultato viene moltiplicato per la matrice dei pesi che collega i neuroni hidden con quelli dell'output layer per ottenere il risultato finale.

(Ogni elemento del risultato è la somma pesata di tutti gli input verso un neurone del layer successivo)

---


# ESERCIZIO

Inizializzare una 'finta' rete neurale:

Aggiungiamo `np.random.seed(42)` in modo da avere sempre la stessa inizializzazione dei pesi in esecuzioni differenti della medesima cella.

1. Definire un vettore di input `x = np.random.rand(3)` e una `threshold = 0.5`
2. Inizializzare random le due matrici di pesi W1 (3x4) e W2 (4x2): le righe sono determinate dal layer precedente (per fare il prodotto si usa `@`; per approfondire vedi regole su prodotto tra vettori e matrici).
3. Moltiplicare l'input x con W1. Il risultato dovrà essere sottoposto alla condizione di threshold: i valori che non superano la threshold devono essere posti a zero.
4. Il risultato `h` filtrato dalla threshold verrà moltiplicato con W2 per ottenere l'output.

In [ ]:
np.random.seed(42) # per avere risultati riproducibili
threshold = 0.5

x = np.random.rand(3)
print(f"vettore di input x:\n{x}")

W_1 = np.random.rand(3, 4)
print(f"matrice di pesi W_1:\n{W_1}")
W_2 = np.random.rand(4, 2)
print(f"matrice di pesi W_2:\n{W_2}")

h = x @ W_1
print(f"output del primo strato h:\n{h}")

mask = h < threshold
h_out = h.copy()
h_out[mask] = 0 # settiamo a 0 i valori sotto la soglia
print(f"output prima della soglia h:\n{h}")
print(f"output del primo strato dopo applicazione della soglia h:\n{h_out}")

y = h_out @ W_2 
print(f"output finale y:\n{y}")




vettore di input x:
[0.37454012 0.95071431 0.73199394]
matrice di pesi W_1:
[[0.59865848 0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258 0.02058449]
 [0.96990985 0.83244264 0.21233911 0.18182497]]
matrice di pesi W_2:
[[0.18340451 0.30424224]
 [0.52475643 0.43194502]
 [0.29122914 0.61185289]
 [0.13949386 0.29214465]]
output del primo strato h:
[1.75767581 1.23926685 0.88703188 0.17441939]
output senza soglia h:
[1.75767581 1.23926685 0.88703188 0.17441939]
output del primo strato con soglia h:
[1.75767581 1.23926685 0.88703188 0.        ]
output finale y:
[1.23100845 1.6127874 ]
